project_id = "kzizdekhohisnixyzlqj"

[functions.enviar-lembretes-missao]
verify_jwt = false

[functions.enviar-email-convite]
verify_jwt = false

[functions.reiniciar_missoes_recorrentes]
verify_jwt = false

[functions.excluir-conta]
verify_jwt = false
